### ISSUE TITLE
support for error bars?

### ISSUE THREAD

**Issue by DrMattG** [mjlajeunesse/juicr#2]
Hi @mjlajeunesse 

Is it possible to extract the width of error bars? I have, for example, a forest plot from a meta-analysis and I want the point estimate and the 95% CI from it. Is that possible?

Cheers
Matt

**Comment by mjlajeunesse** [comment]
Well not directly, for example the video below shows how to extract the point estimate and it's error, but to get the upper (U) 95% CI you would have to for example: point estimate + error to get UCI

https://user-images.githubusercontent.com/12560119/188879256-39087349-3c43-4144-a3f0-aba2ab7dfc4e.mp4
